package assess

import (
	"strings"
	"testing"
)

// The graph is built from CONFIGURATION addresses and the change set uses
// INSTANCE addresses, and nothing joined the two.
//
// `count`, `for_each` and an indexed module call all expand one configuration
// address into several instances: the configuration says
// `terraform_data.counted` and the plan says `terraform_data.counted[0]` and
// `[1]`. The blast radius reported the configuration address, so it named
// resources that DO NOT EXIST in the plan it was describing and counted one
// where there were two. The sequencing annotation looked its dependants up in
// the change set by that same address, found nothing, and said nothing at all.
//
// testdata/expanded-graph.json is one plan carrying every shape, generated by
// real Terraform 1.16.1: a count, a for_each, an indexed module call, and a
// resource joined only by depends_on.

func blastOf(t *testing.T, r Report, addr string) *Annotation {
	t.Helper()
	f := findingFor(t, r, addr)
	for i := range f.Annotations {
		if f.Annotations[i].Code == AnnBlastRadius {
			return &f.Annotations[i]
		}
	}
	return nil
}

// TestTheRadiusNamesInstancesThatExist is the defect, stated as the thing a
// reviewer would do: look up what it named.
func TestTheRadiusNamesInstancesThatExist(t *testing.T) {
	p := loadFixture(t, "expanded-graph.json")

	real := map[string]bool{}
	for _, rc := range p.ResourceChanges {
		real[rc.Address] = true
	}
	// Non-vacuity: the fixture must actually expand something.
	if !real["terraform_data.counted[0]"] || real["terraform_data.counted"] {
		t.Fatalf("the fixture no longer carries an expanded resource")
	}

	a := blastOf(t, Assess(p), "terraform_data.base")
	if a == nil {
		t.Fatal("terraform_data.base has no blast radius, and six resources depend on it")
	}
	for _, name := range a.Paths {
		if !real[name] {
			t.Errorf("the blast radius names %q, which is not a resource in this plan - it is "+
				"a configuration address, and the reader cannot look it up", name)
		}
	}
}

// TestEveryInstanceOfADependantIsCounted. Two instances of one configuration
// are two resources that stop working, not one.
func TestEveryInstanceOfADependantIsCounted(t *testing.T) {
	a := blastOf(t, Assess(loadFixture(t, "expanded-graph.json")), "terraform_data.base")
	if a == nil {
		t.Fatal("no blast radius")
	}
	want := []string{
		"module.app[0].terraform_data.inner",
		"module.app[1].terraform_data.inner",
		"terraform_data.counted[0]",
		"terraform_data.counted[1]",
		"terraform_data.keyed[\"alpha\"]",
		"terraform_data.keyed[\"beta\"]",
		"terraform_data.ordered",
		// Through the module's OUTPUT: base feeds the call's input, the
		// module's resource reads it, its output reads that resource, and this
		// reads the output as a splat over the expanded call.
		"terraform_data.consumer",
	}
	got := append([]string(nil), a.Paths...)
	if !equalStrings(sortedCopy(got), sortedCopy(want)) {
		t.Errorf("blast radius = %v,\nwant %v", sortedCopy(got), sortedCopy(want))
	}
}

// TestDependsOnIsAnEdge. terraform_data.ordered references nothing in any
// expression and is joined to the base only by depends_on - a dependency
// somebody wrote down, which the caveat's "not written down" never covered.
func TestDependsOnIsAnEdge(t *testing.T) {
	a := blastOf(t, Assess(loadFixture(t, "expanded-graph.json")), "terraform_data.base")
	if a == nil {
		t.Fatal("no blast radius")
	}
	found := false
	for _, n := range a.Paths {
		if n == "terraform_data.ordered" {
			found = true
		}
	}
	if !found {
		t.Errorf("blast radius = %v, missing terraform_data.ordered - it depends on the base "+
			"through depends_on, which is a dependency written down and previously unread",
			a.Paths)
	}
}

// TestSequencingReachesExpandedInstances. The silence was downstream of the
// same join: the ordering annotation looks each dependant up in the change set,
// and a configuration address is not in it.
func TestSequencingReachesExpandedInstances(t *testing.T) {
	before, after := both(t, Assess(loadFixture(t, "expanded-graph.json")), "terraform_data.base")
	if before == nil || after == nil {
		t.Fatalf("terraform_data.base orders nothing: before=%v after=%v",
			before != nil, after != nil)
	}
	if len(before.DestroyedFirst) < 6 {
		t.Errorf("DestroyedFirst = %v, want every expanded instance",
			addressesOf(before.DestroyedFirst))
	}
}

// TestAConfigAddressIsReadOffAnInstanceAddress is the join itself, as a table.
// The keys of a for_each can hold dots and brackets, so this cannot be a split
// on ".".
func TestAConfigAddressIsReadOffAnInstanceAddress(t *testing.T) {
	cases := map[string]string{
		"terraform_data.base":                   "terraform_data.base",
		"terraform_data.counted[0]":             "terraform_data.counted",
		`terraform_data.keyed["alpha"]`:         "terraform_data.keyed",
		"module.app[0].terraform_data.inner":    "module.app.terraform_data.inner",
		`module.app["a"].terraform_data.x[2]`:   "module.app.terraform_data.x",
		`terraform_data.k["a.b"]`:               "terraform_data.k",
		`terraform_data.k["]"]`:                 "terraform_data.k",
		`module.m["x.y"].terraform_data.z["p"]`: "module.m.terraform_data.z",
		"data.terraform_remote_state.link":      "data.terraform_remote_state.link",
	}
	for in, want := range cases {
		if got := configAddress(in); got != want {
			t.Errorf("configAddress(%q) = %q, want %q", in, got, want)
		}
	}
}

func sortedCopy(in []string) []string {
	out := append([]string(nil), in...)
	for i := range out {
		for j := i + 1; j < len(out); j++ {
			if out[j] < out[i] {
				out[i], out[j] = out[j], out[i]
			}
		}
	}
	return out
}

var _ = strings.TrimSpace
