package assess

import (
	"strings"
	"testing"
)

// The graph is built from CONFIGURATION addresses and the change set uses
// INSTANCE addresses, and nothing joined the two.
//
// `count`, `for_each` and an indexed module call all expand one configuration
// address into several instances: the configuration says
// `terraform_data.counted` and the plan says `terraform_data.counted[0]` and
// `[1]`. The blast radius reported the configuration address, so it named
// resources that DO NOT EXIST in the plan it was describing and counted one
// where there were two. The sequencing annotation looked its dependants up in
// the change set by that same address, found nothing, and said nothing at all.
//
// testdata/expanded-graph.json is one plan carrying every shape, generated by
// real Terraform 1.16.1: a count, a for_each, an indexed module call, and a
// resource joined only by depends_on.

func blastOf(t *testing.T, r Report, addr string) *Annotation {
	t.Helper()
	f := findingFor(t, r, addr)
	for i := range f.Annotations {
		if f.Annotations[i].Code == AnnBlastRadius {
			return &f.Annotations[i]
		}
	}
	return nil
}

// TestTheRadiusNamesInstancesThatExist is the defect, stated as the thing a
// reviewer would do: look up what it named.
func TestTheRadiusNamesInstancesThatExist(t *testing.T) {
	p := loadFixture(t, "expanded-graph.json")

	real := map[string]bool{}
	for _, rc := range p.ResourceChanges {
		real[rc.Address] = true
	}
	// Non-vacuity: the fixture must actually expand something.
	if !real["terraform_data.counted[0]"] || real["terraform_data.counted"] {
		t.Fatalf("the fixture no longer carries an expanded resource")
	}

	a := blastOf(t, Assess(p), "terraform_data.base")
	if a == nil {
		t.Fatal("terraform_data.base has no blast radius, and six resources depend on it")
	}
	for _, name := range a.Paths {
		if !real[name] {
			t.Errorf("the blast radius names %q, which is not a resource in this plan - it is "+
				"a configuration address, and the reader cannot look it up", name)
		}
	}
}

// TestEveryInstanceOfADependantIsCounted. Two instances of one configuration
// are two resources that stop working, not one.
func TestEveryInstanceOfADependantIsCounted(t *testing.T) {
	a := blastOf(t, Assess(loadFixture(t, "expanded-graph.json")), "terraform_data.base")
	if a == nil {
		t.Fatal("no blast radius")
	}
	want := []string{
		"module.app[0].terraform_data.inner",
		"module.app[1].terraform_data.inner",
		"terraform_data.counted[0]",
		"terraform_data.counted[1]",
		"terraform_data.keyed[\"alpha\"]",
		"terraform_data.keyed[\"beta\"]",
		"terraform_data.ordered",
		// Through the module's OUTPUT: base feeds the call's input, the
		// module's resource reads it, its output reads that resource, and this
		// reads the output as a splat over the expanded call.
		"terraform_data.consumer",
	}
	got := append([]string(nil), a.Paths...)
	if !equalStrings(sortedCopy(got), sortedCopy(want)) {
		t.Errorf("blast radius = %v,\nwant %v", sortedCopy(got), sortedCopy(want))
	}
}

// TestDependsOnIsAnEdge. terraform_data.ordered references nothing in any
// expression and is joined to the base only by depends_on - a dependency
// somebody wrote down, which the caveat's "not written down" never covered.
func TestDependsOnIsAnEdge(t *testing.T) {
	a := blastOf(t, Assess(loadFixture(t, "expanded-graph.json")), "terraform_data.base")
	if a == nil {
		t.Fatal("no blast radius")
	}
	found := false
	for _, n := range a.Paths {
		if n == "terraform_data.ordered" {
			found = true
		}
	}
	if !found {
		t.Errorf("blast radius = %v, missing terraform_data.ordered - it depends on the base "+
			"through depends_on, which is a dependency written down and previously unread",
			a.Paths)
	}
}

// TestSequencingReachesExpandedInstances. The silence was downstream of the
// same join: the ordering annotation looks each dependant up in the change set,
// and a configuration address is not in it.
func TestSequencingReachesExpandedInstances(t *testing.T) {
	before, after := both(t, Assess(loadFixture(t, "expanded-graph.json")), "terraform_data.base")
	if before == nil || after == nil {
		t.Fatalf("terraform_data.base orders nothing: before=%v after=%v",
			before != nil, after != nil)
	}
	if len(before.DestroyedFirst) < 6 {
		t.Errorf("DestroyedFirst = %v, want every expanded instance",
			addressesOf(before.DestroyedFirst))
	}
}

// TestAConfigAddressIsReadOffAnInstanceAddress is the join itself, as a table.
// The keys of a for_each can hold dots and brackets, so this cannot be a split
// on ".".
func TestAConfigAddressIsReadOffAnInstanceAddress(t *testing.T) {
	cases := map[string]string{
		"terraform_data.base":                   "terraform_data.base",
		"terraform_data.counted[0]":             "terraform_data.counted",
		`terraform_data.keyed["alpha"]`:         "terraform_data.keyed",
		"module.app[0].terraform_data.inner":    "module.app.terraform_data.inner",
		`module.app["a"].terraform_data.x[2]`:   "module.app.terraform_data.x",
		`terraform_data.k["a.b"]`:               "terraform_data.k",
		`terraform_data.k["]"]`:                 "terraform_data.k",
		`module.m["x.y"].terraform_data.z["p"]`: "module.m.terraform_data.z",
		"data.terraform_remote_state.link":      "data.terraform_remote_state.link",
	}
	for in, want := range cases {
		if got := configAddress(in); got != want {
			t.Errorf("configAddress(%q) = %q, want %q", in, got, want)
		}
	}
}

func sortedCopy(in []string) []string {
	out := append([]string(nil), in...)
	for i := range out {
		for j := i + 1; j < len(out); j++ {
			if out[j] < out[i] {
				out[i], out[j] = out[j], out[i]
			}
		}
	}
	return out
}

var _ = strings.TrimSpace

// reachOfAddr is the blast radius of one address, as a sorted address list.
func reachOfAddr(t *testing.T, r Report, addr string) []string {
	t.Helper()
	a := blastOf(t, r, addr)
	if a == nil {
		return nil
	}
	return sortedCopy(a.Paths)
}

// TestSelectingOneInstanceDoesNotDependOnAllOfThem is the first false
// dependency Astra found, and the root cause of two of them.
//
// Terraform exports a reference AND its parents: reading
// terraform_data.keyed["one"].output gives both that and a bare
// terraform_data.keyed. Expanding the bare one made every instance a
// dependency, so replacing keyed["two"] claimed a resource that reads
// keyed["one"] would be affected. Terraform's graph has no such edge.
func TestSelectingOneInstanceDoesNotDependOnAllOfThem(t *testing.T) {
	r := Assess(loadFixture(t, "graph-precision.json"))

	if got := reachOfAddr(t, r, `terraform_data.keyed["one"]`); !equalStrings(got, []string{"terraform_data.picks_one"}) {
		t.Errorf(`keyed["one"] reaches %v, want only picks_one`, got)
	}
	if got := reachOfAddr(t, r, `terraform_data.keyed["two"]`); len(got) != 0 {
		t.Errorf(`keyed["two"] reaches %v, and nothing reads it`, got)
	}
}

// TestReadingOneModuleOutputDoesNotDependOnAllOfThem is the same root cause
// through a module. module.apple exports a and b; the caller reads only a.
func TestReadingOneModuleOutputDoesNotDependOnAllOfThem(t *testing.T) {
	r := Assess(loadFixture(t, "graph-precision.json"))

	got := reachOfAddr(t, r, "module.apple.terraform_data.hidden")
	for _, a := range got {
		if a == "terraform_data.reads_a" {
			t.Errorf("replacing the resource behind output b claims terraform_data.reads_a, "+
				"which reads output a: %v", got)
		}
	}
	if !contains(reachOfAddr(t, r, "module.apple.terraform_data.a"), "terraform_data.reads_a") {
		t.Error("the resource behind output a does not reach the caller that reads it")
	}
}

// TestAModuleOutputForwardedThroughAWrapperIsFollowed. A wrapper's output names
// a child's, so resolving one output can need another that has not been walked.
func TestAModuleOutputForwardedThroughAWrapperIsFollowed(t *testing.T) {
	r := Assess(loadFixture(t, "graph-precision.json"))
	got := reachOfAddr(t, r, "module.wrapper.module.child.terraform_data.a")
	if !contains(got, "terraform_data.reads_wrapped") {
		t.Errorf("the resource behind the forwarded output reaches %v, missing the caller "+
			"that reads the wrapper's output", got)
	}
}

// TestADependencyTravelsIntoANestedModule. The base feeds the wrapper's input,
// which feeds the child's, which the child's resources read.
func TestADependencyTravelsIntoANestedModule(t *testing.T) {
	got := reachOfAddr(t, Assess(loadFixture(t, "graph-precision.json")), "terraform_data.base")
	for _, want := range []string{
		"module.apple.terraform_data.a",
		"module.wrapper.module.child.terraform_data.a",
	} {
		if !contains(got, want) {
			t.Errorf("terraform_data.base reaches %v, missing %s", got, want)
		}
	}
}

// TestAZeroCountResourceIsNotACasualty. `count = 0` declares a resource and
// produces none, so naming it makes "N resources in this plan depend on it"
// false - a reader looking it up finds nothing.
func TestAZeroCountResourceIsNotACasualty(t *testing.T) {
	p := loadFixture(t, "graph-precision.json")
	for _, rc := range p.ResourceChanges {
		if strings.Contains(rc.Address, "terraform_data.never") {
			t.Fatalf("%s is in the plan, so this fixture no longer has a zero-count resource",
				rc.Address)
		}
	}
	for _, a := range reachOfAddr(t, Assess(p), "terraform_data.base") {
		if strings.Contains(a, "never") {
			t.Errorf("the blast radius names %q, which has count = 0 and is not in the plan", a)
		}
	}
}

func contains(hay []string, needle string) bool {
	for _, h := range hay {
		if h == needle {
			return true
		}
	}
	return false
}

// TestExpansionExpressionsAndModuleDependsOnAreEdges covers the two inputs
// Terraform exports OUTSIDE an expression map, both of which were unread.
//
//   - count and for_each live in their own fields, so walking `expressions`
//     never saw them. A resource whose very EXISTENCE depends on another is as
//     dependent as one that reads an attribute.
//   - depends_on on a module CALL applies to everything the module declares,
//     and lives on the call rather than on any resource inside it.
func TestExpansionExpressionsAndModuleDependsOnAreEdges(t *testing.T) {
	got := reachOfAddr(t, Assess(loadFixture(t, "graph-expansion.json")), "terraform_data.base")
	want := []string{
		"module.ordered.terraform_data.inner",
		"terraform_data.counted[0]",
		"terraform_data.counted[1]",
		`terraform_data.eached["a"]`,
		`terraform_data.eached["b"]`,
	}
	if !equalStrings(got, sortedCopy(want)) {
		t.Errorf("terraform_data.base reaches\n %v\nwant\n %v", got, sortedCopy(want))
	}
}
