package assess

import (
	"strings"
	"testing"

	tfjson "github.com/hashicorp/terraform-json"
)

// The graph is built from CONFIGURATION addresses and the change set uses
// INSTANCE addresses, and nothing joined the two.
//
// `count`, `for_each` and an indexed module call all expand one configuration
// address into several instances: the configuration says
// `terraform_data.counted` and the plan says `terraform_data.counted[0]` and
// `[1]`. The blast radius reported the configuration address, so it named
// resources that DO NOT EXIST in the plan it was describing and counted one
// where there were two. The sequencing annotation looked its dependants up in
// the change set by that same address, found nothing, and said nothing at all.
//
// testdata/expanded-graph.json is one plan carrying every shape, generated by
// real Terraform 1.16.1: a count, a for_each, an indexed module call, and a
// resource joined only by depends_on.

func blastOf(t *testing.T, r Report, addr string) *Annotation {
	t.Helper()
	f := findingFor(t, r, addr)
	for i := range f.Annotations {
		if f.Annotations[i].Code == AnnBlastRadius {
			return &f.Annotations[i]
		}
	}
	return nil
}

// TestTheRadiusNamesInstancesThatExist is the defect, stated as the thing a
// reviewer would do: look up what it named.
func TestTheRadiusNamesInstancesThatExist(t *testing.T) {
	p := loadFixture(t, "expanded-graph.json")

	real := map[string]bool{}
	for _, rc := range p.ResourceChanges {
		real[rc.Address] = true
	}
	// Non-vacuity: the fixture must actually expand something.
	if !real["terraform_data.counted[0]"] || real["terraform_data.counted"] {
		t.Fatalf("the fixture no longer carries an expanded resource")
	}

	a := blastOf(t, Assess(p), "terraform_data.base")
	if a == nil {
		t.Fatal("terraform_data.base has no blast radius, and six resources depend on it")
	}
	for _, name := range a.Paths {
		if !real[name] {
			t.Errorf("the blast radius names %q, which is not a resource in this plan - it is "+
				"a configuration address, and the reader cannot look it up", name)
		}
	}
}

// TestEveryInstanceOfADependantIsCounted. Two instances of one configuration
// are two resources that stop working, not one.
func TestEveryInstanceOfADependantIsCounted(t *testing.T) {
	a := blastOf(t, Assess(loadFixture(t, "expanded-graph.json")), "terraform_data.base")
	if a == nil {
		t.Fatal("no blast radius")
	}
	want := []string{
		"module.app[0].terraform_data.inner",
		"module.app[1].terraform_data.inner",
		"terraform_data.counted[0]",
		"terraform_data.counted[1]",
		"terraform_data.keyed[\"alpha\"]",
		"terraform_data.keyed[\"beta\"]",
		"terraform_data.ordered",
		// Through the module's OUTPUT: base feeds the call's input, the
		// module's resource reads it, its output reads that resource, and this
		// reads the output as a splat over the expanded call.
		"terraform_data.consumer",
	}
	got := append([]string(nil), a.Paths...)
	if !equalStrings(sortedCopy(got), sortedCopy(want)) {
		t.Errorf("blast radius = %v,\nwant %v", sortedCopy(got), sortedCopy(want))
	}
}

// TestDependsOnIsAnEdge. terraform_data.ordered references nothing in any
// expression and is joined to the base only by depends_on - a dependency
// somebody wrote down, which the caveat's "not written down" never covered.
func TestDependsOnIsAnEdge(t *testing.T) {
	a := blastOf(t, Assess(loadFixture(t, "expanded-graph.json")), "terraform_data.base")
	if a == nil {
		t.Fatal("no blast radius")
	}
	found := false
	for _, n := range a.Paths {
		if n == "terraform_data.ordered" {
			found = true
		}
	}
	if !found {
		t.Errorf("blast radius = %v, missing terraform_data.ordered - it depends on the base "+
			"through depends_on, which is a dependency written down and previously unread",
			a.Paths)
	}
}

// TestSequencingReachesExpandedInstances. The silence was downstream of the
// same join: the ordering annotation looks each dependant up in the change set,
// and a configuration address is not in it.
func TestSequencingReachesExpandedInstances(t *testing.T) {
	before, after := both(t, Assess(loadFixture(t, "expanded-graph.json")), "terraform_data.base")
	if before == nil || after == nil {
		t.Fatalf("terraform_data.base orders nothing: before=%v after=%v",
			before != nil, after != nil)
	}
	if len(before.DestroyedFirst) < 6 {
		t.Errorf("DestroyedFirst = %v, want every expanded instance",
			addressesOf(before.DestroyedFirst))
	}
}

// TestAConfigAddressIsReadOffAnInstanceAddress is the join itself, as a table.
// The keys of a for_each can hold dots and brackets, so this cannot be a split
// on ".".
func TestAConfigAddressIsReadOffAnInstanceAddress(t *testing.T) {
	cases := map[string]string{
		"terraform_data.base":                   "terraform_data.base",
		"terraform_data.counted[0]":             "terraform_data.counted",
		`terraform_data.keyed["alpha"]`:         "terraform_data.keyed",
		"module.app[0].terraform_data.inner":    "module.app.terraform_data.inner",
		`module.app["a"].terraform_data.x[2]`:   "module.app.terraform_data.x",
		`terraform_data.k["a.b"]`:               "terraform_data.k",
		`terraform_data.k["]"]`:                 "terraform_data.k",
		`module.m["x.y"].terraform_data.z["p"]`: "module.m.terraform_data.z",
		"data.terraform_remote_state.link":      "data.terraform_remote_state.link",
	}
	for in, want := range cases {
		if got := configAddress(in); got != want {
			t.Errorf("configAddress(%q) = %q, want %q", in, got, want)
		}
	}
}

func sortedCopy(in []string) []string {
	out := append([]string(nil), in...)
	for i := range out {
		for j := i + 1; j < len(out); j++ {
			if out[j] < out[i] {
				out[i], out[j] = out[j], out[i]
			}
		}
	}
	return out
}

var _ = strings.TrimSpace

// reachOfAddr is the blast radius of one address, as a sorted address list.
func reachOfAddr(t *testing.T, r Report, addr string) []string {
	t.Helper()
	a := blastOf(t, r, addr)
	if a == nil {
		return nil
	}
	return sortedCopy(a.Paths)
}

// TestSelectingOneInstanceDoesNotDependOnAllOfThem is the first false
// dependency Astra found, and the root cause of two of them.
//
// Terraform exports a reference AND its parents: reading
// terraform_data.keyed["one"].output gives both that and a bare
// terraform_data.keyed. Expanding the bare one made every instance a
// dependency, so replacing keyed["two"] claimed a resource that reads
// keyed["one"] would be affected. Terraform's graph has no such edge.
func TestSelectingOneInstanceDoesNotDependOnAllOfThem(t *testing.T) {
	r := Assess(loadFixture(t, "graph-precision.json"))

	if got := reachOfAddr(t, r, `terraform_data.keyed["one"]`); !equalStrings(got, []string{"terraform_data.picks_one"}) {
		t.Errorf(`keyed["one"] reaches %v, want only picks_one`, got)
	}
	if got := reachOfAddr(t, r, `terraform_data.keyed["two"]`); len(got) != 0 {
		t.Errorf(`keyed["two"] reaches %v, and nothing reads it`, got)
	}
}

// TestReadingOneModuleOutputDoesNotDependOnAllOfThem is the same root cause
// through a module. module.apple exports a and b; the caller reads only a.
func TestReadingOneModuleOutputDoesNotDependOnAllOfThem(t *testing.T) {
	r := Assess(loadFixture(t, "graph-precision.json"))

	got := reachOfAddr(t, r, "module.apple.terraform_data.hidden")
	for _, a := range got {
		if a == "terraform_data.reads_a" {
			t.Errorf("replacing the resource behind output b claims terraform_data.reads_a, "+
				"which reads output a: %v", got)
		}
	}
	if !contains(reachOfAddr(t, r, "module.apple.terraform_data.a"), "terraform_data.reads_a") {
		t.Error("the resource behind output a does not reach the caller that reads it")
	}
}

// TestAModuleOutputForwardedThroughAWrapperIsFollowed. A wrapper's output names
// a child's, so resolving one output can need another that has not been walked.
func TestAModuleOutputForwardedThroughAWrapperIsFollowed(t *testing.T) {
	r := Assess(loadFixture(t, "graph-precision.json"))
	got := reachOfAddr(t, r, "module.wrapper.module.child.terraform_data.a")
	if !contains(got, "terraform_data.reads_wrapped") {
		t.Errorf("the resource behind the forwarded output reaches %v, missing the caller "+
			"that reads the wrapper's output", got)
	}
}

// TestADependencyTravelsIntoANestedModule. The base feeds the wrapper's input,
// which feeds the child's, which the child's resources read.
func TestADependencyTravelsIntoANestedModule(t *testing.T) {
	got := reachOfAddr(t, Assess(loadFixture(t, "graph-precision.json")), "terraform_data.base")
	for _, want := range []string{
		"module.apple.terraform_data.a",
		"module.wrapper.module.child.terraform_data.a",
	} {
		if !contains(got, want) {
			t.Errorf("terraform_data.base reaches %v, missing %s", got, want)
		}
	}
}

// TestAZeroCountResourceIsNotACasualty. `count = 0` declares a resource and
// produces none, so naming it makes "N resources in this plan depend on it"
// false - a reader looking it up finds nothing.
func TestAZeroCountResourceIsNotACasualty(t *testing.T) {
	p := loadFixture(t, "graph-precision.json")
	for _, rc := range p.ResourceChanges {
		if strings.Contains(rc.Address, "terraform_data.never") {
			t.Fatalf("%s is in the plan, so this fixture no longer has a zero-count resource",
				rc.Address)
		}
	}
	for _, a := range reachOfAddr(t, Assess(p), "terraform_data.base") {
		if strings.Contains(a, "never") {
			t.Errorf("the blast radius names %q, which has count = 0 and is not in the plan", a)
		}
	}
}

// TestExpansionExpressionsAndModuleDependsOnAreEdges covers the two inputs
// Terraform exports OUTSIDE an expression map, both of which were unread.
//
//   - count and for_each live in their own fields, so walking `expressions`
//     never saw them. A resource whose very EXISTENCE depends on another is as
//     dependent as one that reads an attribute.
//   - depends_on on a module CALL applies to everything the module declares,
//     and lives on the call rather than on any resource inside it.
func TestExpansionExpressionsAndModuleDependsOnAreEdges(t *testing.T) {
	got := reachOfAddr(t, Assess(loadFixture(t, "graph-expansion.json")), "terraform_data.base")
	want := []string{
		"module.ordered.terraform_data.inner",
		"terraform_data.counted[0]",
		"terraform_data.counted[1]",
		`terraform_data.eached["a"]`,
		`terraform_data.eached["b"]`,
	}
	if !equalStrings(got, sortedCopy(want)) {
		t.Errorf("terraform_data.base reaches\n %v\nwant\n %v", got, sortedCopy(want))
	}
}

// TestAReferenceIsSplitOnItsRealSeparators. A for_each key is an arbitrary
// string written into the reference in quotes, so a dot inside one is not a
// separator - strings.Split built the malformed graph key
// `terraform_data.base["a` and the edge went nowhere.
//
// Tested directly because a plan with a dotted key that is also referenced
// specifically is a narrow shape, and the parser is the thing being claimed.
func TestAReferenceIsSplitOnItsRealSeparators(t *testing.T) {
	cases := map[string][]string{
		"terraform_data.base":                   {"terraform_data", "base"},
		`terraform_data.base["a.b"].output`:     {"terraform_data", `base["a.b"]`, "output"},
		`terraform_data.base["a][b"]`:           {"terraform_data", `base["a][b"]`},
		`terraform_data.k["say \"hi\""]`:        {"terraform_data", `k["say \"hi\""]`},
		`terraform_data.k["back\\slash"]`:       {"terraform_data", `k["back\\slash"]`},
		"module.app[0].terraform_data.x":        {"module", "app[0]", "terraform_data", "x"},
		`module.m["x.y"].terraform_data.z["p"]`: {"module", `m["x.y"]`, "terraform_data", `z["p"]`},
		"var.seed":                              {"var", "seed"},
		"":                                      nil,
		"terraform_data.unterminated[":          {"terraform_data", "unterminated["},
	}
	for in, want := range cases {
		got := splitRef(in)
		if !equalStrings(got, want) {
			t.Errorf("splitRef(%q) = %#v, want %#v", in, got, want)
		}
	}
}

// TestConfigAddressAndSplitRefAgree. configAddress strips indices and splitRef
// keeps them, and mostSpecific compares one against the other - so a
// disagreement between the two would silently stop the bare-reference filter
// working, which is the false-dependency defect returning.
func TestConfigAddressAndSplitRefAgree(t *testing.T) {
	for _, ref := range []string{
		`terraform_data.base["a.b"]`,
		"module.app[0].terraform_data.x",
		`module.m["x.y"].terraform_data.z["p"]`,
	} {
		segs := splitRef(ref)
		rebuilt := strings.Join(segs, ".")
		if rebuilt != ref {
			t.Errorf("splitRef(%q) rejoins to %q", ref, rebuilt)
		}
		var stripped []string
		for _, s := range segs {
			stripped = append(stripped, configAddress(s))
		}
		if want := configAddress(ref); strings.Join(stripped, ".") != want {
			t.Errorf("stripping each segment of %q gives %q, and configAddress gives %q",
				ref, strings.Join(stripped, "."), want)
		}
	}
}

// TestAWholeInstanceReadDoesNotDependOnEveryInstance. The same-length case the
// first filter missed.
//
// `terraform_data.base["a.b"]` read whole - with no attribute after it - is
// exported beside a bare `terraform_data.base`, and BOTH have two segments.
// Requiring the covering reference to be longer kept the bare one, so it
// expanded to every instance and a consumer of one key was listed under the
// other.
func TestAWholeInstanceReadDoesNotDependOnEveryInstance(t *testing.T) {
	r := Assess(loadFixture(t, "graph-edges.json"))
	if got := reachOfAddr(t, r, `terraform_data.base["other"]`); len(got) != 0 {
		t.Errorf(`base["other"] reaches %v, and nothing reads it`, got)
	}
	if got := reachOfAddr(t, r, `terraform_data.base["a.b"]`); !equalStrings(got, []string{"terraform_data.whole_read"}) {
		t.Errorf(`base["a.b"] reaches %v, want only whole_read`, got)
	}
}

// TestDependsOnAModuleReachesWhatItDeclares. A module reference is otherwise a
// reference to its OUTPUTS, so `depends_on = [module.empty]` on a module that
// exports nothing resolved to nothing at all. An explicit dependency on a
// module is a dependency on the resources in it, exported or not.
func TestDependsOnAModuleReachesWhatItDeclares(t *testing.T) {
	got := reachOfAddr(t, Assess(loadFixture(t, "graph-edges.json")), "module.empty.terraform_data.hidden")
	if !contains(got, "terraform_data.after_empty") {
		t.Errorf("the resource inside module.empty reaches %v, and a resource depends_on the "+
			"whole module", got)
	}
}

// TestAnIndexedOutputTraversalIsStillThatOutput. Reading
// `module.obj.items[0].id` names the output `items`; looking up `items[0]`
// found nothing and the dependency vanished.
func TestAnIndexedOutputTraversalIsStillThatOutput(t *testing.T) {
	got := reachOfAddr(t, Assess(loadFixture(t, "graph-edges.json")), "module.obj.terraform_data.backing")
	if !contains(got, "terraform_data.reads_item") {
		t.Errorf("the resource behind the output reaches %v, and a resource reads an indexed "+
			"element of it", got)
	}
}

// TestAnOrphanedInstanceGetsNoDependencies. Reducing a count leaves the
// instances above the new one being destroyed and nothing else - the current
// configuration does not declare them.
//
// Expanding the configuration address to every instance in the change set gave
// each of them every dependency the resource has TODAY, so terraform_data.b[1],
// which is only being deleted, was listed as a casualty of the resource b now
// reads and ordered against it. Terraform's graph connects that destroy to the
// provider and nothing else.
//
// The exclusion is narrow on purpose: an instance that is ONLY being deleted
// while another instance of the same configuration is not. A plan that destroys
// everything has every instance delete-only, and excluding those would empty
// the graph for the case a blast radius matters most - which the second half
// of this test holds.
func TestAnOrphanedInstanceGetsNoDependencies(t *testing.T) {
	p := loadFixture(t, "graph-orphan.json")

	// Non-vacuity: the fixture must carry an orphan beside a kept sibling.
	var orphan, kept bool
	for _, rc := range p.ResourceChanges {
		if rc.Address == "terraform_data.b[1]" && rc.Change.Actions.Delete() {
			orphan = true
		}
		if rc.Address == "terraform_data.b[0]" && !rc.Change.Actions.Delete() {
			kept = true
		}
	}
	if !orphan || !kept {
		t.Fatalf("the fixture no longer has an orphan beside a kept sibling: orphan=%v kept=%v",
			orphan, kept)
	}

	got := reachOfAddr(t, Assess(p), "terraform_data.a[0]")
	if contains(got, "terraform_data.b[1]") {
		t.Errorf("terraform_data.a[0] reaches %v, and b[1] is only being deleted - this "+
			"configuration does not declare it", got)
	}
	if !contains(got, "terraform_data.b[0]") {
		t.Errorf("terraform_data.a[0] reaches %v, missing b[0], which reads it", got)
	}
}

// TestAPlanThatDestroysEverythingReportsNoRadius, which is a real loss and the
// side of the contract this tool has to come down on.
//
// A `terraform destroy` orders its destroys in reverse dependency order, so
// the relationships are real there and a blast radius would be worth having.
// The exemption that kept them tested for "nothing in this plan is kept" - and
// Astra showed that cannot tell a destroy plan from one that sets every count
// to zero, where the surviving instances never had the dependency the
// configuration now declares. Nothing in the file distinguishes the two.
//
// So the edges go, in both. The radius may be short and may never be invented,
// and a report that states a dependency somebody's plan does not have is the
// failure this whole contract exists to prevent.
func TestAPlanThatDestroysEverythingReportsNoRadius(t *testing.T) {
	p := loadFixture(t, "graph-orphan.json")
	for _, rc := range p.ResourceChanges {
		rc.Change.Actions = tfjson.Actions{tfjson.ActionDelete}
	}
	for _, f := range Assess(p).Findings {
		if a, ok := annotationFor(f, AnnBlastRadius); ok {
			t.Errorf("%s reports a blast radius of %v on a plan where everything is being "+
				"deleted, and the configuration describes what will exist", f.Address, a.Paths)
		}
	}
}

// TestABroadReadAndASelectiveOneAreTold. The case accepted as an unavoidable
// ambiguity in an earlier round, which was not one.
//
// Terraform exports a reference with its parents and does not deduplicate, so
// each narrow chain contributes exactly one occurrence of each ancestor. A
// bare reference appearing MORE often than the chains beneath it is a reading
// of its own: `[values(base)[*].id, base["a.b"].id]` exports `base` twice and
// `base["a.b"].id` alone exports it once. The information was in the file.
func TestABroadReadAndASelectiveOneAreTold(t *testing.T) {
	r := Assess(loadFixture(t, "graph-mixed.json"))

	// The broad read reaches both instances, because it reads all of them.
	other := reachOfAddr(t, r, `terraform_data.base["other"]`)
	if !contains(other, "terraform_data.mixed") {
		t.Errorf(`base["other"] reaches %v, and mixed reads the whole collection`, other)
	}
	if contains(other, "terraform_data.selective") {
		t.Errorf(`base["other"] reaches %v, and selective reads only "a.b"`, other)
	}

	// And the selective one still reaches only what selects it.
	ab := reachOfAddr(t, r, `terraform_data.base["a.b"]`)
	for _, want := range []string{"terraform_data.mixed", "terraform_data.selective"} {
		if !contains(ab, want) {
			t.Errorf(`base["a.b"] reaches %v, missing %s`, ab, want)
		}
	}
}

// TestTwoSelectiveChainsAreNotABroadRead. Counting occurrences was not enough.
//
// `[base["a.b"], base["a.b"].id]` is two traversals of the SAME instance, and
// both chains end in a bare `terraform_data.base` - so it appeared twice with
// only one chain longer than it, and the surplus looked like a read of the
// whole collection. Segmenting the list into chains says there are two
// traversals and neither is bare.
func TestTwoSelectiveChainsAreNotABroadRead(t *testing.T) {
	r := Assess(loadFixture(t, "graph-two-chains.json"))
	if got := reachOfAddr(t, r, `terraform_data.base["other"]`); len(got) != 0 {
		t.Errorf(`base["other"] reaches %v, and nothing reads it`, got)
	}
	if got := reachOfAddr(t, r, `terraform_data.base["a.b"]`); !equalStrings(got, []string{"terraform_data.twice"}) {
		t.Errorf(`base["a.b"] reaches %v, want the resource that reads it twice`, got)
	}
}

// TestACountReducedToZeroLeavesNoDependants, and a resource removed from a
// module the same way.
//
// A delete-only instance will not exist after the apply, so the configuration
// - which describes what WILL exist - says nothing about it. Testing that
// against a surviving sibling missed a count reduced to zero, where there is
// none, and missed a resource deleted from a module entirely.
func TestACountReducedToZeroLeavesNoDependants(t *testing.T) {
	p := loadFixture(t, "graph-zero-count.json")

	// Non-vacuity: both shapes have to be in the fixture.
	var zeroCount, removed bool
	for _, rc := range p.ResourceChanges {
		if rc.Address == "terraform_data.b[0]" && rc.Change.Actions.Delete() {
			zeroCount = true
		}
		if rc.Address == "module.m.terraform_data.removed" && rc.Change.Actions.Delete() {
			removed = true
		}
	}
	if !zeroCount || !removed {
		t.Fatalf("the fixture no longer carries both shapes: zeroCount=%v removed=%v",
			zeroCount, removed)
	}

	got := reachOfAddr(t, Assess(p), "terraform_data.a[0]")
	for _, gone := range []string{
		"terraform_data.b[0]", "terraform_data.b[1]", "module.m.terraform_data.removed",
	} {
		if contains(got, gone) {
			t.Errorf("terraform_data.a[0] reaches %v, and %s is only being deleted - this "+
				"configuration does not declare it", got, gone)
		}
	}
	// And the module resource that IS still declared, reached through the
	// call's depends_on.
	if !contains(got, "module.m.terraform_data.kept") {
		t.Errorf("terraform_data.a[0] reaches %v, missing the module resource that survives "+
			"and whose call depends on it", got)
	}
}

// TestASingletonOrphanInventsNothing. The way round the exclusion.
//
// An address the plan holds is used as itself rather than expanded, which is
// right for a specific reference - and it meant a singleton given an empty
// for_each, which is one instance being deleted and nothing else, still
// produced an edge when the configuration named it directly. The two paths
// into an address have to agree about which instances exist.
func TestASingletonOrphanInventsNothing(t *testing.T) {
	p := loadFixture(t, "graph-singleton-orphan.json")

	var orphan bool
	for _, rc := range p.ResourceChanges {
		if rc.Address == "terraform_data.b" && rc.Change.Actions.Delete() {
			orphan = true
		}
	}
	if !orphan {
		t.Fatal("the fixture no longer carries a singleton being deleted")
	}

	f := findingFor(t, Assess(p), "terraform_data.a")
	for _, a := range f.Annotations {
		switch a.Code {
		case AnnBlastRadius, AnnDestroyedBefore, AnnChangedAfter:
			t.Errorf("terraform_data.a claims %q, and the only thing naming it is an "+
				"instance this plan deletes and the configuration no longer declares",
				a.Summary)
		}
	}
}
