#!/usr/bin/env python3
"""Render a real terrakit report as an SVG for the README.

The capture is generated by running the tool, never by hand-writing what
its output looks like. A README that shows output the binary does not
actually produce is worse than one with no screenshot at all, and this
tool's whole claim is that its presentation is trustworthy.

Re-run it whenever the renderer changes:

    go build -o /tmp/tv ./cmd/tv && python3 assets/_gen/demo.py
"""

import subprocess
import sys
from pathlib import Path

from rich.console import Console
from rich.text import Text

ROOT = Path(__file__).resolve().parent.parent.parent
OUT = ROOT / "assets"
BIN = "/tmp/terrakit"
WIDTH = 86

# The fixture shows the two findings that most need seeing before anyone
# installs this: a critical data-loss escalation, and a rename whose moved
# block is missing, with the evidence behind it.
#
# Not "things nothing else does", which is what this comment used to say
# and was wrong. tfautomv has detected create/delete pairs since 2022, and
# tfplan2md renders a plan for review. What is particular here is the
# ranking and the fact that neither of those is the subject of a screenshot
# a reader has to trust - the capture is generated by running the binary.
FIXTURE = ROOT / "testdata" / "demo.json"


def capture(args):
    env = {"FORCE_COLOR": "1", "COLUMNS": str(WIDTH), "PATH": "/usr/bin:/bin"}
    r = subprocess.run([BIN, *args], capture_output=True, text=True, env=env)
    if r.returncode not in (0, 1):
        sys.exit(f"{BIN} {' '.join(args)} failed ({r.returncode}): {r.stderr}")
    return r.stdout


def to_svg(ansi, out_name, title):
    # tv has already wrapped to COLUMNS and drawn its own tree column, so
    # rich must not re-flow it. Give the console more width than the
    # content and print line by line with wrapping off - otherwise rich
    # rewraps at its own boundary and a continuation line escapes the
    # indent it was aligned to.
    console = Console(record=True, width=WIDTH + 6, file=open("/dev/null", "w"))
    for line in ansi.rstrip("\n").split("\n"):
        console.print(Text.from_ansi(line), overflow="ignore", crop=False, no_wrap=True)
    svg = console.export_svg(title=title)
    (OUT / out_name).write_text(svg)
    print(f"wrote assets/{out_name}")


def main():
    if not Path(BIN).exists():
        sys.exit(f"{BIN} not found - run: go build -o {BIN} ./cmd/tv")
    to_svg(capture([str(FIXTURE)]), "demo.svg", "tv plan.json")


if __name__ == "__main__":
    main()
